### ISSUE TITLE
Configuration question

### ISSUE THREAD

**Issue by micah** [hloeung/matterircd-complete#1]
Hey - thanks for making this!

Just one question, at the top in the comments you say:
```
# For the full matterircd_complete experience, your matterircd.toml
# should have SuffixContext=true, ThreadContext="mattermost", and
# Unicode=true.
```

Do you know if it will work if `PrefixContext = true` and `SuffixContext = true` ? I ask because I have `PrefixContext` set, but not `SuffixContext` and I'm unsure how they would work together.

thanks!

**Comment by hloeung** [comment]
@micah, yes, it should work with either `PrefixContext` or `SuffixContext` with the later being what I currently use. It's one or the other for matterircd - as in, you want the thread ID to either be at the start of the messages or at the end.

**Comment by micah** [comment]
On 2021-10-31 14:01:02, Haw Loeung wrote:
> @micah, yes, it should work with either `PrefixContext` or `SuffixContext` with the later being what I currently use. It's one or the other for matterircd - as in, you want the thread ID to either be at the start of the messages or at the end.

Thanks for the reply, you are right, I tried setting mine to
SuffixContext and your script does work. 

I also set `ThreadContext = "mattermost"` as you suggest, however, I
don't see anymore the ThreadID indicators anymore. I think maybe they
are there, but at a color that does not appear on my dark terminal. Do
you have a color setting in irssi that makes those visible? Otherwise I
dont know which thread I'm replying to :D

**Comment by micah** [comment]
On 2021-11-01 08:47:26, micah wrote:
> I also set `ThreadContext = "mattermost"` as you suggest, however, I
> don't see anymore the ThreadID indicators anymore. I think maybe they
> are there, but at a color that does not appear on my dark terminal. Do
> you have a color setting in irssi that makes those visible? Otherwise I
> dont know which thread I'm replying to :D

Indeed, either the unicode or the control characters involved in this
makes it so it appears dark on my terminal, which is dark, if I capture
it, it looks like this:

`[M-bM-^FM-*@@3yb4e6d4kp86bm9dkr9oish4ka]$`

M-b = 0xE2, M-^F = 0x86, M-* = 0xAA
and 0x86 of those is a control character in ISO-8859-1

I guess one 'easy' solution would be to turn Unicode off, but what
functionality from matterircd-complete is lost when I do that?

**Comment by micah** [comment]
On 2021-11-01 13:37:04, micah wrote:
> On 2021-11-01 08:47:26, micah wrote:
>> I also set `ThreadContext = "mattermost"` as you suggest, however, I
>> don't see anymore the ThreadID indicators anymore. I think maybe they
>> are there, but at a color that does not appear on my dark terminal. Do
>> you have a color setting in irssi that makes those visible? Otherwise I
>> dont know which thread I'm replying to :D
>
> Indeed, either the unicode or the control characters involved in this
> makes it so it appears dark on my terminal, which is dark, if I capture
> it, it looks like this:
>
> `[M-bM-^FM-*@@3yb4e6d4kp86bm9dkr9oish4ka]$`
>
> M-b = 0xE2, M-^F = 0x86, M-* = 0xAA
> and 0x86 of those is a control character in ISO-8859-1
>
> I guess one 'easy' solution would be to turn Unicode off, but what
> functionality from matterircd-complete is lost when I do that?

Ok, I found that this is color 14 from
https://github.com/hloeung/matterircd-complete/blob/master/matterircd_complete.pl#L141

if I change it to '10' for example, then I can see it. 

perhaps this should be configurable with a setting!

**Comment by hloeung** [comment]
heh yeah, the idea is to make it sort of invisible or not to be confused with the original message itself. So doing that with ANSI colour sequence.

Sure, I can make this a configurable setting for sure!

**Comment by hloeung** [comment]
@micah, okay all fixed. I even made it the default color you selected as I'm probably one of the few that likes it to be less visible unless needed:

https://github.com/hloeung/matterircd-complete/commit/9b6fc62d090ddb3f44e4e8787e67e1a8c849816e
